version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "iot-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5wfmr8bt9yax"
s3_prefix = "iot-demo"
region = "ap-southeast-2"
profile = "iot-play"
capabilities = "CAPABILITY_IAM"
image_repositories = []
